language: python
cache: pip
matrix:
  include:
  - os: osx
    language: generic
  - python: pypy
install:
  - scripts/travis.sh pip install --upgrade pip
  - scripts/travis.sh pip install --upgrade setuptools
  - scripts/travis.sh pip install --upgrade --requirement=requirements-travis.txt
  - scripts/travis.sh LC_ALL=C pip install .
script:
  - scripts/travis.sh make check
  - scripts/travis.sh make test
after_success:
  - scripts/travis.sh coveralls
branches:
  except:
    - /^[0-9]/
